Numpy Arrays

In [2]:
#Array in 1 Dimension

import numpy as np
a = np.array([1,2,3])
print(a)

#Array in 2 Dimensions

b = np.array([[1,2,3], [4,5,6]])
print (b)


#Same number in an array of dimension x and y

import numpy as np
np.full((2,2), 5)


[1 2 3]
[[1 2 3]
 [4 5 6]]


array([[5, 5],
       [5, 5]])

In [3]:
Initialize the elements x X y array to 0

np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
#Arrange no's between X and Y with an interval of Z

np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
#Random numbers  b/w X and Y

np.random.random((2,4))

array([[0.8304718 , 0.64826869, 0.40759532, 0.93738083],
       [0.97218395, 0.03579466, 0.01700614, 0.17876239]])

In [13]:
#Array Mathematics

#Addition

np.sum([3,2])
np.sum([[2,3],[4,5]])

14

In [15]:
np.sum([[2,3],[4,5]],axis=0)

array([6, 8])

In [16]:
np.sum([[2,3],[4,5]],axis=1)

array([5, 9])

In [17]:
#Array Comparison (element-wise comparison)
a=[1,2,3]
b=[2,3,3]
c=[1,4,3]
np.equal(a,b)

array([False, False,  True])

In [19]:
#Array-wise comparison
a=[1,3,3]
b=[1,3,3]
c=[1,4,3]
np.array_equal(a,b)

True

In [21]:
#Concept of Broadcasting
import numpy as np
a=np.array([[1,2,3],[2,3,3],[4,5,6]])
b=np.array([2,2,3])
print("First Array:", a)
print("Second Array: ", b)
print("First array+Second Array:" ,a+b)

First Array: [[1 2 3]
 [2 3 3]
 [4 5 6]]
Second Array:  [2 2 3]
First array+Second Array: [[3 4 6]
 [4 5 6]
 [6 7 9]]


#Array Manipulation

In [23]:
a=np.array([1,2,3])
b=np.array([2,2,3])
#Concatenate of two arrays
np.concatenate((a,b))

array([1, 2, 3, 2, 2, 3])

In [24]:
#Stack array row-wise : horizontally
np.hstack((a,b))

array([1, 2, 3, 2, 2, 3])

In [25]:
#Stack array row-wise : Vertically
np.vstack((a,b))

array([[1, 2, 3],
       [2, 2, 3]])

In [26]:
#Stack array Column-wise
np.column_stack((a,b))

array([[1, 2],
       [2, 2],
       [3, 3]])

In [29]:
#Splitting Array

a=np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [36]:
a=np.arange(16).reshape(4,4)
print(a)
print(np.hsplit(a,2))
print(np.hsplit(a,np.array([3])))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [39]:
#Indexing ANd Slicing

a=np.array([[1,3,2],[3,4,5],[5,6,7]])
a[0]
a[:1]

array([[1, 3, 2]])

In [42]:
a[:2,1:]

array([[3, 2],
       [4, 5]])

In [44]:
a[1:,1:]

array([[4, 5],
       [6, 7]])